"""empty message

Revision ID: 02e3c8f29799
Revises: 82e144a78965
Create Date: 2022-08-01 15:22:07.310188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e3c8f29799'
down_revision = '82e144a78965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('status', sa.Enum('todo', 'inProgress', 'done', name='statustype'), nullable=True))
    op.add_column('project', sa.Column('task', sa.String(length=200), nullable=True))
    op.drop_column('project', 'todo')
    op.drop_column('project', 'done')
    op.drop_column('project', 'inProgress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('inProgress', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('done', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('todo', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('project', 'task')
    op.drop_column('project', 'status')
    # ### end Alembic commands ###
