"""empty message

Revision ID: 651910e33a22
Revises: a73e71cb790f
Create Date: 2022-08-15 14:15:49.663999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651910e33a22'
down_revision = 'a73e71cb790f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('in_and_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person', sa.String(length=200), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clock_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Full_Name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff')
    op.drop_table('in_and_out')
    # ### end Alembic commands ###
