"""empty message

Revision ID: 673566aed71f
Revises: 5f6e82173adc
Create Date: 2022-10-30 16:27:45.561110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673566aed71f'
down_revision = '5f6e82173adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('calendar', sa.Column('name', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar', 'name')
    op.drop_column('calendar', 'quantity')
    # ### end Alembic commands ###
