"""empty message

Revision ID: 67da28caddcb
Revises: 5cc497fca0ea
Create Date: 2022-08-15 16:13:58.398530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67da28caddcb'
down_revision = '5cc497fca0ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('in_and_out', sa.Column('clock_in', sa.Boolean(), nullable=False))
    op.drop_column('in_and_out', 'clock_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('in_and_out', sa.Column('clock_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('in_and_out', 'clock_in')
    # ### end Alembic commands ###
