"""empty message

Revision ID: 6e222e398fe7
Revises: bd145830d07a
Create Date: 2022-08-29 23:03:59.221597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e222e398fe7'
down_revision = 'bd145830d07a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('start_ticket_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_ticket_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('table_time_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('table_time_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('important_changes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['item'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('item')
    # ### end Alembic commands ###
