"""empty message

Revision ID: 7aa417071438
Revises: 651910e33a22
Create Date: 2022-08-15 15:12:58.591760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa417071438'
down_revision = '651910e33a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('Full_name', sa.String(length=200), nullable=False))
    op.drop_column('staff', 'Full_Name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('Full_Name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('staff', 'Full_name')
    # ### end Alembic commands ###
