"""empty message

Revision ID: 82e144a78965
Revises: 6b4c50c71d3d
Create Date: 2022-07-31 16:11:17.496005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e144a78965'
down_revision = '6b4c50c71d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo', sa.String(length=200), nullable=True),
    sa.Column('inProgress', sa.String(length=200), nullable=True),
    sa.Column('done', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
