"""empty message

Revision ID: 89669a3384f2
Revises: 6e222e398fe7
Create Date: 2022-08-29 23:10:56.223250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89669a3384f2'
down_revision = '6e222e398fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('dish_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'dish_name')
    # ### end Alembic commands ###
