"""empty message

Revision ID: a73e71cb790f
Revises: 7581a4fd6e7a
Create Date: 2022-08-10 20:59:42.203990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73e71cb790f'
down_revision = '7581a4fd6e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('description', sa.String(length=200), nullable=False))
    op.add_column('calendar', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('calendar', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('calendar', 'selection')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('selection', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('calendar', 'start_time')
    op.drop_column('calendar', 'end_time')
    op.drop_column('calendar', 'description')
    # ### end Alembic commands ###
