"""empty message

Revision ID: b7f5fca2ee55
Revises: c7c4ea7f4eff
Create Date: 2022-08-17 14:42:06.297843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f5fca2ee55'
down_revision = 'c7c4ea7f4eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('in_and_out', sa.Column('person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'in_and_out', 'staff', ['person_id'], ['id'])
    op.drop_column('in_and_out', 'person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('in_and_out', sa.Column('person', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'in_and_out', type_='foreignkey')
    op.drop_column('in_and_out', 'person_id')
    # ### end Alembic commands ###
