"""empty message

Revision ID: bd145830d07a
Revises: b7f5fca2ee55
Create Date: 2022-08-22 15:23:06.829741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd145830d07a'
down_revision = 'b7f5fca2ee55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('in_and_out', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('in_and_out', 'name')
    # ### end Alembic commands ###
