"""empty message

Revision ID: ee63b57fb460
Revises: f10953f4b517
Create Date: 2022-08-31 16:27:03.068575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee63b57fb460'
down_revision = 'f10953f4b517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'dish_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('dish_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
