"""empty message

Revision ID: f10953f4b517
Revises: de0397922e33
Create Date: 2022-08-31 16:22:54.096222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10953f4b517'
down_revision = 'de0397922e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'item_id')
    )
    op.drop_constraint('order_item_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('item', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_item_fkey', 'order', 'item', ['item'], ['id'])
    op.drop_table('order_item')
    # ### end Alembic commands ###
